name: gxt

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: make
      run: |
        del ./gamefiles/TEXT/
        cd ./utils/gxt
        build.bat
        convtxd -x particle.txd
      shell: cmd
    - name: upload
      uses: actions/upload-artifact@v4.6.0
      with:
        path: gamefiles/TEXT/
    - name: txd
      uses: actions/upload-artifact@v4.6.0
      with:
        name: txd
        path: utils/gxt/
